begin;
select plan(4);
select ok(has_column_privilege('service_role','public.barbers','id','select'),'Upload and reuse gateways can verify profile ownership by barber ID');
select ok(not has_table_privilege('service_role','public.barbers','select'),'Profile lookup does not grant unrestricted roster reads');
select ok(not has_column_privilege('service_role','public.barbers','active','update'),'Resource lookup cannot alter booking eligibility');
set local role service_role;
select lives_ok($$select id from public.barbers where id='hassan'$$,'The real gateway query is authorized');
reset role;
select * from finish();
rollback;
