import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = new URL('../../', import.meta.url)
const stampFile = new URL('shared/cms-release.ts', root)
// Complete local dependency set of cms-studio. External imports are pinned in these files.
export const releaseFiles = [
  'supabase/functions/cms-studio/index.ts',
  'supabase/functions/cms-studio/copyAsset.ts',
  'supabase/functions/cms-studio/deno.json',
  'shared/cms.ts',
  'shared/cms-markup.ts',
  'shared/cms-built-assets.ts',
]

export function releaseDigest(read = (path) => readFileSync(new URL(path, root), 'utf8')) {
  const hash = createHash('sha256')
  for (const path of releaseFiles)
    hash.update(path + '\0' + read(path).replaceAll('\r\n', '\n') + '\0')
  return hash.digest('hex')
}

export async function verifyBackend(url, expected, request = fetch) {
  const response = await request(new URL('/functions/v1/cms-studio', url), {
    method: 'OPTIONS',
    headers: { Origin: 'https://bladeblendstudio.se', 'Access-Control-Request-Method': 'POST' },
    signal: globalThis.AbortSignal.timeout(15000),
  })
  if (!response.ok || response.headers.get('x-cms-release') !== expected)
    throw new Error(
      'CMS backend does not match this checkout. Deploy cms-studio from this commit before deploying the frontend.',
    )
}

export async function main(mode = process.argv[2] ?? 'verify') {
  if (!['stamp', 'check', 'verify'].includes(mode))
    throw new Error('Expected stamp, check, or verify')
  const digest = releaseDigest()
  const content = `// Generated by npm run cms:stamp; checked in CI. Do not edit manually.\nexport const CMS_RELEASE = '${digest}'\n`
  if (mode === 'stamp') {
    writeFileSync(stampFile, content)
    return
  }
  if (readFileSync(stampFile, 'utf8') !== content)
    throw new Error(
      'CMS release stamp is stale. Run npm run cms:stamp and commit the updated stamp.',
    )
  if (mode === 'verify') {
    const { loadEnv } = await import('vite')
    const env = loadEnv('production', fileURLToPath(root), 'VITE_')
    const url =
      process.env.CMS_RELEASE_URL ?? process.env.VITE_SUPABASE_URL ?? env.VITE_SUPABASE_URL
    if (!url) throw new Error('VITE_SUPABASE_URL or CMS_RELEASE_URL is required')
    await verifyBackend(url, digest)
    console.log(`CMS backend verified: ${digest.slice(0, 12)}`)
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main()
