// Source-owned assets; this inventory contains paths, never embedded file bytes.
export const CMS_BUILT_ASSETS = [
  '/favicon.svg',
  '/fonts/InterVariable-Latin.woff2',
  '/fonts/PlayfairDisplay-Latin-400.woff2',
  '/fonts/PlayfairDisplay-Latin-700-Italic.woff2',
  '/fonts/PlayfairDisplay-Latin-700.woff2',
  '/icons.svg',
  '/icons/calendar.badge.plus.svg',
  '/icons/calendar.svg',
  '/icons/checkmark.circle.fill.svg',
  '/icons/checkmark.svg',
  '/icons/chevron.down.svg',
  '/icons/chevron.left.svg',
  '/icons/chevron.right.svg',
  '/icons/clock.svg',
  '/icons/knc-logo-pole.svg',
  '/icons/mappin.circle.fill.svg',
  '/icons/moon.svg',
  '/icons/phone.svg',
  '/icons/sun.max.svg',
  '/og-image.png',
] as const
